---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bubble
  labels:
    app: sorting
    cheese: bubble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorting
      task: bubble
  template:
    metadata:
      labels:
        app: sorting
        task: bubble
        version: v0.0.1
    spec:
      containers:
      - name: bubble
        image: andriimaslianko/bubble:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bubble
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: sorting
    task: bubble